/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pkg.tuan5;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class jfrBookSupliers extends javax.swing.JFrame {

    /**
     * Creates new form jfrBookSupliers
     */
    public jfrBookSupliers() {
        initComponents();
        showBookSupliersInTable();
    }

    //ham show data len table
    private void showBookSupliersInTable() {
        List<BookSupliers> listBooks = Controller.getAllBoosBookSuplierses();
        DefaultTableModel model = (DefaultTableModel) tblBookSupliers.getModel();
        // System.out.println("model");
        Object[] book = new Object[7];
        // System.out.println("oblect");
        for (int i = 0; i < listBooks.size(); i++) {
            //System.out.println("1");
            book[0] = listBooks.get(i).getId();
            // System.out.println("2");
            book[1] = listBooks.get(i).getName();
            //System.out.println("3");
            book[2] = listBooks.get(i).getType();
            //System.out.println("4");
            book[3] = listBooks.get(i).getAddress();
            //System.out.println("5");
            book[4] = listBooks.get(i).getContract();
            //System.out.println("6");
            book[5] = listBooks.get(i).getEmail();
            // System.out.println("7");
            book[6] = listBooks.get(i).getRemakes();
            // System.out.println("8");
            model.addRow(book);
            //System.out.println("9");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jckBooks = new javax.swing.JCheckBox();
        jckNewspappers = new javax.swing.JCheckBox();
        jckJouralsAndMangazines = new javax.swing.JCheckBox();
        txtAdress = new javax.swing.JTextField();
        txtContract = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        araRemakes = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBookSupliers = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Book Suppliers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(244, 244, 244))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("ID");

        jLabel3.setText("Name");

        jLabel4.setText("Type");

        jLabel5.setText("Address");

        jLabel6.setText("Contract");

        jLabel7.setText("Email");

        jLabel8.setText("Remakes");

        jckBooks.setText("Books");

        jckNewspappers.setText("Newspapper");

        jckJouralsAndMangazines.setText("Jounrals and Mangazines");

        araRemakes.setColumns(20);
        araRemakes.setRows(5);
        jScrollPane1.setViewportView(araRemakes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContract, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jckBooks)
                                .addGap(18, 18, 18)
                                .addComponent(jckNewspappers)))
                        .addGap(18, 18, 18)
                        .addComponent(jckJouralsAndMangazines)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jckBooks)
                    .addComponent(jckNewspappers)
                    .addComponent(jckJouralsAndMangazines))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtContract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNew)
                .addGap(45, 45, 45)
                .addComponent(btnSave)
                .addGap(45, 45, 45)
                .addComponent(btnUpdate)
                .addGap(47, 47, 47)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblBookSupliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "type", "Address", "contact", "email", "remakes"
            }
        ));
        tblBookSupliers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookSupliersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblBookSupliers);
        if (tblBookSupliers.getColumnModel().getColumnCount() > 0) {
            tblBookSupliers.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBookSupliersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookSupliersMouseClicked
        // TODO add your handling code here:
        txtId.setEnabled(false);
        btnSave.setEnabled(false);
        int i = tblBookSupliers.getSelectedRow();
        TableModel model = tblBookSupliers.getModel();
        txtId.setText(model.getValueAt(i, 0).toString());
        txtName.setText(model.getValueAt(i, 1).toString());
        txtAdress.setText(model.getValueAt(i, 3).toString());
        txtContract.setText(model.getValueAt(i, 4).toString());
        txtEmail.setText(model.getValueAt(i, 5).toString());
        araRemakes.setText(model.getValueAt(i, 6).toString());

        String typeBook = model.getValueAt(i, 2).toString();
        switch (typeBook) {
            case "Books":
                jckBooks.setSelected(true);
                jckJouralsAndMangazines.setSelected(false);
                jckNewspappers.setSelected(false);
                break;
            case "Newspapper":
                jckBooks.setSelected(false);
                jckJouralsAndMangazines.setSelected(false);
                jckNewspappers.setSelected(true);
                break;
            case "Jounrals and Mangazines":
                jckBooks.setSelected(false);
                jckJouralsAndMangazines.setSelected(true);
                jckNewspappers.setSelected(false);
                break;
            case "Books, Newspapper":
                jckBooks.setSelected(true);
                jckJouralsAndMangazines.setSelected(false);
                jckNewspappers.setSelected(true);
                break;
            case "Books, Jounrals and Mangazines":
                jckBooks.setSelected(true);
                jckJouralsAndMangazines.setSelected(true);
                jckNewspappers.setSelected(false);
                break;
            case "Newspapper, Jounrals and Mangazines":
                jckBooks.setSelected(false);
                jckJouralsAndMangazines.setSelected(true);
                jckNewspappers.setSelected(true);
                break;
            case "Books, Newspapper, Jounrals and Mangazines":
                jckBooks.setSelected(true);
                jckJouralsAndMangazines.setSelected(true);
                jckNewspappers.setSelected(true);
                break;
        }
    }//GEN-LAST:event_tblBookSupliersMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        txtId.setEnabled(false);
        String type = null;
         if (jckJouralsAndMangazines.isSelected() && jckBooks.isSelected() && jckNewspappers.isSelected()) {
            type = "Books, Newspapper, Jounrals and Mangazines";
        }else if (jckNewspappers.isSelected() && jckBooks.isSelected()) {
            type = "Books, Newspapper";
        } else if (jckNewspappers.isSelected() && jckJouralsAndMangazines.isSelected()) {
            type = "Newspapper, Jounrals and Mangazines";
        } else if (jckJouralsAndMangazines.isSelected() && jckBooks.isSelected()) {
            type = "Books, Jounrals and Mangazines";
        }else  if (jckBooks.isSelected()) {
            type = "Books";
        }else if (jckNewspappers.isSelected()) {
            type = "Newspapper";
        } else if (jckJouralsAndMangazines.isSelected()) {
            type = "Jounrals and Mangazines";
        }
        
        BookSupliers book = new BookSupliers();
        book.setId((txtId.getText()));
        book.setName((txtName.getText()));
        book.setType(type);
        book.setAddress((txtAdress.getText()));
        book.setContract((txtContract.getText()));
        book.setEmail((txtEmail.getText()));
        book.setRemakes((araRemakes.getText()));

        Controller.addBooks(book);
        JOptionPane.showMessageDialog(null, "Inserted Sucessfully!");
        DefaultTableModel model = (DefaultTableModel) tblBookSupliers.getModel();
        model.setRowCount(0);
        showBookSupliersInTable();

        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        txtId.setEnabled(true);
        txtId.setText("");
        txtName.setText("");
        txtAdress.setText("");
        txtContract.setText("");
        txtEmail.setText("");
        araRemakes.setText("");

        jckBooks.setSelected(false);
        jckNewspappers.setSelected(false);
        jckJouralsAndMangazines.setSelected(false);

        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null, "Are You Sure", "DELETE", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            int rowIndex = tblBookSupliers.getSelectedRow();
            String id = tblBookSupliers.getModel().getValueAt(rowIndex, 0).toString();

            Controller.deleteBooks(id);
            DefaultTableModel model = (DefaultTableModel) tblBookSupliers.getModel();
            model.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Deleted Sucessfully!");
            showBookSupliersInTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String type = null;
         if (jckJouralsAndMangazines.isSelected() && jckBooks.isSelected() && jckNewspappers.isSelected()) {
            type = "Books, Newspapper, Jounrals and Mangazines";
        }else if (jckNewspappers.isSelected() && jckBooks.isSelected()) {
            type = "Books, Newspapper";
        } else if (jckNewspappers.isSelected() && jckJouralsAndMangazines.isSelected()) {
            type = "Newspapper, Jounrals and Mangazines";
        } else if (jckJouralsAndMangazines.isSelected() && jckBooks.isSelected()) {
            type = "Books, Jounrals and Mangazines";
        }else  if (jckBooks.isSelected()) {
            type = "Books";
        }else if (jckNewspappers.isSelected()) {
            type = "Newspapper";
        } else if (jckJouralsAndMangazines.isSelected()) {
            type = "Jounrals and Mangazines";
        }
        
        BookSupliers book = new BookSupliers();
        book.setId((txtId.getText()));
        book.setName((txtName.getText()));
        book.setType(type);
        book.setAddress((txtAdress.getText()));
        book.setContract((txtContract.getText()));
        book.setEmail((txtEmail.getText()));
        book.setRemakes((araRemakes.getText()));

        int rowIndex = tblBookSupliers.getSelectedRow();
        String id = tblBookSupliers.getModel().getValueAt(rowIndex, 0).toString();
        
        Controller.updateBooks(book , id);
        JOptionPane.showMessageDialog(null, "Update Sucessfully!");
        DefaultTableModel model = (DefaultTableModel) tblBookSupliers.getModel();
        model.setRowCount(0);
        showBookSupliersInTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
         int ret = JOptionPane.showConfirmDialog(null, "Thoát Chương Trình", "Thoát", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrBookSupliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrBookSupliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrBookSupliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrBookSupliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrBookSupliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea araRemakes;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jckBooks;
    private javax.swing.JCheckBox jckJouralsAndMangazines;
    private javax.swing.JCheckBox jckNewspappers;
    private javax.swing.JTable tblBookSupliers;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtContract;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
